#!/bin/sh

exec 2>&1

rundir=$(dirname $(readlink -m "$PWD/run"))
envdir="$rundir/env"
root=$(dirname $(dirname "$rundir"))
port=$(echo "$PWD" | cut -d- -f2)

export GOPATH="$HOME/go"

cd $root

go build && chpst -e $envdir ./manveru.name -port $port
